COLOR_BG = "#0F0F1A"
COLOR_SURFACE = "#1E1E3A"
COLOR_SIDEBAR = "#1A1A30"
COLOR_SIDEBAR_HOVER = "#2A2A4A"
COLOR_SIDEBAR_ACTIVE = "#2D2D50"

COLOR_BLUE = "#7C3AED"
COLOR_BLUE_HOVER = "#6D28D9"
COLOR_GREEN = "#10B981"
COLOR_RED = "#EF4444"
COLOR_YELLOW = "#F59E0B"

COLOR_TEXT = "#E8EAED"
COLOR_TEXT_SECONDARY = "#9CA3AF"
COLOR_BORDER = "#3D3D5C"

FONT_FAMILY = "Segoe UI"
FONT_TITLE = (FONT_FAMILY, 18, "bold")
FONT_SECTION = (FONT_FAMILY, 13, "bold")
FONT_BODY = (FONT_FAMILY, 12)
FONT_CAPTION = (FONT_FAMILY, 10)
